name: jsonexample
description: A demonstration of JSON parsing

dependencies:

  json_annotation: ^0.2.3
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.1

  flutter:
    sdk: flutter

dev_dependencies:

  build_runner: ^0.8.0
  json_serializable: ^0.5.0
  built_value_generator: ^5.5.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
